### ISSUE TITLE
Enhancements - todo list

### ISSUE THREAD

**Issue by RARgames** [RARgames/4gaBoards#1]
- [x] Ctrl+Enter when creating a task opens edit menu
- [x] Sum cards in column, in board
- [x] Colapse column to save screen space
- [x] Always visible scroll bar
- [x] Move tasks to a different column when hovering over +Add another card with a task,
- [x] Add support for dragging cards into collapsed collums
- [x] AddCard should not close when there is something inside + Improved AddCard experience
- [x] Bug: Multiline list titles break board view
- [x] Bug: Cards added to list appear at wrong order when filtering is on + card sorting when filtering is on (getfilteredordered)
- [x] Add column names to cards at the top + add faster column switching when editing a card
- [x] Images and labels below the title
- [x] Don't auto-create card cover images (Show image only in the description by default)
- [x] Enhance pages e.g. login page - center login form
- [x] BUG: Escape on card edit causing full leave
- [x] Change the current layout of editing a task: Edit menu opens on the right of the screen, you can still scroll through other issues, select them, move, etc.
- [x] Replace MD editor - DescriptionEdit.jsx - Better spellchecker and dark mode (https://github.com/uiwjs/react-md-editor) 
- [x] Add sidebar for choosing projects/boards
- [x] Better edit menus (pencil button) - more compact menus without extra texts
- [x] Full dark mode: alternative colors for task etc.

Important:
- [x] Disable labels duplicates, add quick filter by label/user from cardModal, delete label x button (clicking member or label should filter by it, clicking x close to label should remove it)
- [ ] Parse #Label @Member when creating a task and automatically add labels and members on creation
- [ ] Enhance MD editor - mentions, task list, remember opened mode (https://github.com/uiwjs/react-md-editor/issues/420)
- [ ] Simplify language for advanced users
- [ ] Github issues synchronized board - on setup get all issues from github and copy to the internal database, then 2-way sync (Columns can be saved using labels with prefixes, not displayed in 4ga Boards, if needed) Each user needs its GIthub authorization to use the board, without that the synchronized board is read-only (redo label colors).
- [ ] Add github-like task close option (like issues) Default action should be close, which can move the task to a new hidden by default column: archived. Delete is possible by using other button - more destructive action, as you cannot get the task back.
- [ ] Add task numbering in each board (so each task has its id: 1, 2, 3, and you can see a small # 1, # 2 somewhere near the task name. It can speed up finding tasks, also added to filter by) In a synchronized board it, clicking task number should open github issue. (Open questions: how to handle issues+PRs?)
- [ ] Convert - [ ] from description to a working task list
- [ ] Github-like confirm deleting whole board to further prevent accidental deletion

For later:
- [ ] Filter task by name (the same field should allow #Label, @Member, task_number filtering)
- [x] Update npm dependencies
- [ ] Right click to open context menus
- [ ] Better dashboard with project/boards stats
- [ ] User groups: user group can be added to the project or the board (instead of to the whole system), Individual users, user groups can be added to the project/board. Probably a structure [Organization -> Team -> User] is a better option and could help in the future.

Sidebar should be available as an alternate layout. In sidebar there are projects. Each project has its own dashboard and boards in a list.

In the project dashboard each board has its own box with the following info:
- name of the board
- members
- board actions
- scrollable stats: columns and number of cards
- activity graph for last 30 days?

and additional box where you can create new board

**Comment by xdxd121xdxd** [comment]
Good ideas

**Comment by RARgames** [comment]
Should be duplicates of other issues - to check

**Comment by RARgames** [comment]
Closed as all sub-tasks are now in separate issues
