### ISSUE TITLE
4ga Boards Current Roadmap

### ISSUE THREAD

**Issue by RARgames** [RARgames/4gaBoards#452]
Past three weeks we have slowed down our development cycle to make it easier to introduce 4ga Boards to new users. 
We are still providing smaller features, bug fixes and security updates.
This process is expected to continue for another ~2 weeks, after that we plan to go back to Standard Development Cycle (New Features as described in https://4gaboards.com/features with coming soon tag)

Our current roadmap:
- [x] Import/Export
- [x] Standarized inputs errors 
- [x] User Getting Started Project
- [x] 4ga Boards Homepage:  https://4gaboards.com/#home
- [x] 4ga Boards Other Pages
- [x] 4ga Boards Page - Contact
- [x] 4ga Boards Page - Legal
- [x] 4ga Boards Full Experience (for now)
- [x] Migrate 4ga Boards Docs
